run:
  deadline: 5m
  issues-exit-code: 1
  skip-dirs:
    - data

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: "conqueror"
  gocritic:
    enabled-tags:
      - experimental
      - opinionated
