version: '3'

services:
  conqueror:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conqueror
    hostname: conqueror
    stdin_open: true
    tty: true
    restart: on-failure
    environment:
      PORT: 8080
      DB_HOST: conqueror-db:3306
      DB_NAME: conqueror
      DB_USER: user
      DB_PASSWORD: 12345Q
      MIGRATIONS_DIR: /app/migrations
    volumes:
      - ${WORK_DIR}/bin:/app/bin
      - ${WORK_DIR}/data/migrations:/app/migrations
    ports:
      - "8080:8080"
    depends_on:
      - conqueror-db

  conqueror-db:
    image: mysql:8.0
    container_name: conqueror-db
    hostname: conqueror-db
    user: "$USER_ID"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conqueror
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345Q
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${WORK_DIR}/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
