version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${WORK_DIR}/data/files:/app/files
      - ${WORK_DIR}/~conf/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - conqueror
      - conqueror-client

  conqueror-client:
    build: client
    container_name: conqueror-client
    hostname: conqueror-client
    stdin_open: true
    tty: true
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ${WORK_DIR}/client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - conqueror

  conqueror:
    build: .
    container_name: conqueror
    hostname: conqueror
    stdin_open: true
    tty: true
    restart: on-failure
    environment:
      PORT: 8080
      SECRET: boobz
      FILES_DIR: /app/files
      GIN_MODE: debug
      DB_HOST: conqueror-db:3306
      DB_NAME: conqueror
      DB_USER: user
      DB_PASSWORD: 12345Q
      MIGRATIONS_DIR: /app/migrations
    volumes:
      - ${WORK_DIR}/bin:/app/bin
      - ${WORK_DIR}/data/migrations:/app/migrations
      - ${WORK_DIR}/data/files:/app/files
    ports:
      - "8080:8080"
    depends_on:
      - conqueror-db

  conqueror-db:
    image: mysql:8.0
    container_name: conqueror-db
    hostname: conqueror-db
    user: "$USER_ID"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conqueror
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345Q
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${WORK_DIR}/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
